### PR TITLE
[FIXED JENKINS-32659] Add support for Cloudbees Folder

### PR DESCRIPTION
**Pull request by etiennebec**
Current version only support jobs which are at the root level of Jenkins. This pull request enables launch of job in any level of subfolder. I tested it against Jenkins 1.596.3 and 1.646.

### CODE REVIEW

**Comment by geoffroyjabouley** [comment]
Hi
can this PR be merged and integrated in a new release please? Can we help?

**Comment by etiennebec** [comment]
I wrote three tests cases which check if the job is triggered when it's at the root level / in a folder / in a subfolder. I had to bump the required core version to 1.480 to use Cloudbees Folder in my tests.

**Comment by ddbeatty** [comment]
@ejpenney It looks like you merged all of the pull requests a few days ago.  Will there be a new release of this plug-in soon?

**Comment by ejpenney** [comment]
Yes, I merged a lot of changes into mainline, so I wanted to test the plugin in my Jenkins environment for a few days before releasing it.  So far everything looks OK, probably going to run a release early this week.

**Comment by ddbeatty** [comment]
Sounds good, thanks.

**Comment by etiennebec** [comment]
@ejpenney thanks for adopting this plugin!

**Comment by ejpenney** [comment]
Well, I was hoping for it to be early this week but it looks like I have some access requests to get through.  Every day I get a little bit further, hopefully soon now!

**Comment by ddbeatty** [comment]
Thanks for the update and I agree with etiennebec.  Thanks, for looking after this plugin.

**Comment by ddbeatty** [comment]
@ejpenney Thanks for getting the new version out there.  @etiennebec Thanks for providing this pr.  I have upgraded this plugin and it is now finding our startup job which is in a folder a couple of levels deep.

**Pull request merged**
